#!/bin/bash

# star='k5888_4.1.METALS_-3.3C_1.0O_1.0N_1.0' ; vtb=1.5
# star='k6180_3.7.METALS_-5.6C_4.0O_3.0N_4.0' ; vtb=1.7
# star='k6390_4.4.METALS_-3.2C_1.0O_1.0N_1.0' ; vtb=1.6
 star='test' ; vtb=1.5
#


cd OPTAB
./mkoptab ../tl208sy54/EMPSyo2021/${star}.7
cd ../NLTEpop
./mknlte ../tl208sy54/EMPSyo2021/${star}.7 ${vtb}
cd ../SPECTRA
./mkspec ../tl208sy54/EMPSyo2021/${star}.7 ${vtb}
